apiVersion: v1
kind: Pod
metadata:
  name: jupyter-tensorboard
  labels:
    name: jupyter-tensorboard
  namespace: default
spec:
  containers:
  - name: jupyter-notebook
    image: "606513654560.dkr.ecr.us-east-1.amazonaws.com/tensorflow-notebook:latest"
    ports:
     - containerPort: 8888
    volumeMounts:
    - mountPath: /log
      name: log-dir
  - name: tensorboard
    image: "606513654560.dkr.ecr.us-east-1.amazonaws.com/tensor_dist_server:latest"
    ports:
     - containerPort: 6006
    command: ["python"]
    args: ["-m","tensorflow.tensorboard","--logdir=/log"]
    volumeMounts:
    - mountPath: /log
      name: log-dir
  volumes:
  - name: log-dir
    emptyDir: {}
