FROM ubuntu:16.04

RUN apt-get update
RUN apt-get -y install git python-pip python2.7

RUN pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.1-cp27-none-linux_x86_64.whl
